---
title: "Check LST quality"
author: "Anna Boser"
date: '2022-05-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(here)
library(stringr)
```

## check the quality of the ECOSTRESS LST images
```{r}
files <- list.files(path = here("data", "ECOSTRESS", "int", "celcius"), full.names = TRUE)

pal <- colorRampPalette(c("darkblue", "blue", "steelblue1", "white", "yellow", "orange", "red"))

plot_with_name <- function(raster){
  print(plot(raster, 
             col = pal(50), 
             main=names(raster), 
             zlim=c(0, 60)))
}

plot_batch <- function(batch){
  files <- files[(1:10+(batch*10))]
  rasters <- lapply(files, raster)
  print(lapply(rasters, plot_with_name))
}
```

```{r}
plot_batch(5)
```

```{r}
plot_batch(4)
```

```{r}
plot_batch(6)
```

```{r}
plot_batch(7)
```

```{r}
plot_batch(8)
```

```{r}
plot_batch(9)
```


```{r}
plot_batch(10)
```

```{r}
plot_batch(11)
```

```{r}
plot_batch(12)
```

```{r}
plot_batch(13)
```

```{r}
plot_batch(14)
```

```{r}
plot_batch(15)
```

```{r}
plot_batch(16)
```

```{r}
plot_batch(17)
```

```{r}
plot_batch(18)
```

```{r}
plot_batch(19)
```

```{r}
plot_batch(20)
```

```{r}
plot_batch(20)
```

```{r}
plot_batch(21)
```

```{r}
plot_batch(22)
```

```{r}
plot_batch(23)
```

```{r}
plot_batch(24)
```

```{r}
plot_batch(25)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```

```{r}
plot_batch(35)
```

```{r}
plot_batch(36)
```

```{r}
plot_batch(37)
```

```{r}
plot_batch(38)
```

```{r}
plot_batch(39)
```

```{r}
plot_batch(40)
```

```{r}
plot_batch(41)
```

```{r}
plot_batch(42)
```

```{r}
plot_batch(43)
```

```{r}
plot_batch(44)
```

```{r}
plot_batch(45)
```

```{r}
plot_batch(46)
```

```{r}
plot_batch(47)
```

```{r}
plot_batch(48)
```

```{r}
plot_batch(49)
```

```{r}
plot_batch(50)
```

```{r}
plot_batch(51)
```

```{r}
plot_batch(52)
```

```{r}
plot_batch(53)
```

```{r}
plot_batch(54)
```

```{r}
plot_batch(55)
```

```{r}
plot_batch(56)
```

```{r}
plot_batch(57)
```

```{r}
plot_batch(58)
```

```{r}
plot_batch(59)
```

```{r}
plot_batch(60)
```

```{r}
plot_batch(61)
```

```{r}
plot_batch(62)
```

```{r}
plot_batch(63)
```

```{r}
plot_batch(64)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```

```{r}
plot_batch(26)
```

```{r}
plot_batch(27)
```

```{r}
plot_batch(28)
```

```{r}
plot_batch(29)
```

```{r}
plot_batch(30)
```

```{r}
plot_batch(31)
```

```{r}
plot_batch(32)
```

```{r}
plot_batch(33)
```

```{r}
plot_batch(34)
```